defaults: &defaults
  network_basic_url: https://124.16.141.142
  client_secret: h9LAQKuwdM3oaMhT
  redirect_uri: http://localhost:3000/users/iscasCallback
  client_id: 7
  audit_url: http://192.168.13.29:8080/audit/_single
  codeSearch_url: http://192.168.5.1:8080/codesearch/v1/code
  gitlab_basic_url: http://localhost:3000

development:
  <<: *defaults
  network_basic_url: https://124.16.141.142
  client_secret: h9LAQKuwdM3oaMhT
  redirect_uri: http://localhost:3000/users/iscasCallback
  client_id: 7
  audit_url: http://192.168.13.29:8080/audit/_single
  codeSearch_url: http://192.168.5.1:8080/codesearch/v1/code
  gitlab_basic_url: http://localhost:3000

production:
  <<: *defaults
  network_basic_url: https://124.16.141.142
  client_secret: h9LAQKuwdM3oaMhT
  redirect_uri: http://localhost:3000/users/iscasCallback
  client_id: 7
  audit_url: http://192.168.13.29:8080/audit/_single
  codeSearch_url: http://192.168.5.1:8080/codesearch/v1/code
  gitlab_basic_url: http://localhost:3000

test:
  <<: *defaults
