defaults: &defaults
  network_basic_url: https://124.16.141.142
  client_secret: h9LAQKuwdM3oaMhT
  redirect_uri: http://localhost:3000/users/iscasCallback
  client_id: 7
  gitlab_basic_url: http://localhost:3000
  tmp_office_threshold: 50000000
  tmp_pdf_threshold: 1000000000

development:
  <<: *defaults
  network_basic_url: https://124.16.141.142
  client_secret: h9LAQKuwdM3oaMhT
  redirect_uri: http://localhost:3000/users/iscasCallback
  client_id: 7
  gitlab_basic_url: http://localhost:3000
  tmp_office_threshold: 50000000
  tmp_pdf_threshold: 1000000000

production:
  <<: *defaults
  network_basic_url: https://124.16.141.142
  client_secret: h9LAQKuwdM3oaMhT
  redirect_uri: http://localhost:3000/users/iscasCallback
  client_id: 7
  gitlab_basic_url: http://localhost:3000
  tmp_office_threshold: 50000000
  tmp_pdf_threshold: 1000000000

test:
  <<: *defaults
